// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUZJqfW_PnT1p0Nc8AKvZY-K-yjcHT16w',
    appId: '1:910359904382:web:447ee2cd15bc8ce950d82f',
    messagingSenderId: '910359904382',
    projectId: 'kelltontech-project',
    authDomain: 'kelltontech-project.firebaseapp.com',
    storageBucket: 'kelltontech-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrTGHCEwKGUwRmE33BoKv-vpktOv9e_7I',
    appId: '1:910359904382:android:79e8a40458177c4250d82f',
    messagingSenderId: '910359904382',
    projectId: 'kelltontech-project',
    storageBucket: 'kelltontech-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUCETTYeWFDu0nfff-3ElKPRMC3mgxSg',
    appId: '1:910359904382:ios:bd5fa2fafc3b255050d82f',
    messagingSenderId: '910359904382',
    projectId: 'kelltontech-project',
    storageBucket: 'kelltontech-project.appspot.com',
    iosClientId: '910359904382-4ns1stgb72koms7hotr6mivpvcnhgc0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
