import 'package:flutter_application_1/KnowYourStateApp/states.dart';

class StatesService {
  List<States> getStates() {
    List<States> states = [
      States(
          'Andhra Pradesh',
          'Amaravati',
          '1 November 1956',
          'Visakhapatnam',
          'Telugu',
          26,
          'Y.S. Jaganmohan Reddy',
          'Biswabhusan Harichandan',
          '49,386,799',
          10,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/IN-AP.svg/375px-IN-AP.svg.png'),
      States(
          'Arunachal Pradesh',
          'Itanagar',
          '20 February 1987',
          'Itanagar',
          'English',
          25,
          'Pema Khandu',
          'B.D. Mishra',
          '1,382,611',
          27,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/IN-AR.svg/375px-IN-AR.svg.png'),
      States(
          'Assam',
          'Dispur',
          '26 January 1950',
          'Guwahati',
          'Assamese',
          35,
          'Himanta Biswa Sarma',
          'Jagdish Mukhi',
          '31,169,272',
          15,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/IN-AS.svg/375px-IN-AS.svg.png'),
      States(
          'Bihar',
          'Patna',
          '22 March 1912',
          'Patna',
          'Hindi',
          38,
          'Nitish Kumar',
          'Phagu Chauhan',
          '104,099,452',
          3,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/IN-BR.svg/375px-IN-BR.svg.png'),
      States(
          'Chhattisgarh',
          'Raipur',
          '1 November 2000',
          'Raipur',
          'Hindi',
          33,
          'Bhupesh Baghel',
          'Anusuiya Uikey',
          '29,436,231',
          17,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/IN-CT.svg/375px-IN-CT.svg.png'),
      States(
          'Goa',
          'Panaji',
          '30 May 1987',
          'Vasco da Gama',
          'Konkani',
          2,
          'Pramod Sawat',
          'P.S.Sreedharan',
          '1,458,545',
          26,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IN-GA.svg/375px-IN-GA.svg.png'),
      States(
          'Gujarat',
          'Gandhinagar',
          '1 May 1960',
          'Ahmedabad',
          'Gujarati',
          33,
          'Bhupendrabhai Patel',
          'Acharya Dev Vrat',
          '60,439,692',
          5,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/IN-GJ.svg/375px-IN-GJ.svg.png'),
      States(
          'Haryana',
          'Chandigarh',
          '1 Novemnber 1966',
          'Faridabad',
          'Hindi & Haryanvi',
          22,
          'Manohar Lal Khattar',
          'Bandaru Dattatreya',
          '25,353,081',
          18,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/IN-HR.svg/375px-IN-HR.svg.png'),
      States(
          'Himachal Pradesh',
          'Shimla',
          '1 November 1956',
          'Shimla',
          'Hindi',
          12,
          'Jai Ram Thakur',
          'Rajendra Arlekar',
          '6,864,145',
          21,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/IN-HP.svg/375px-IN-HP.svg.png'),
      States(
          'Jharkhand',
          'Ranchi',
          '15 November',
          'Jamshedpur',
          'Hindi',
          24,
          'Hemant Soren',
          'Ramesh Bais',
          '32,988,134',
          14,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/IN-JH.svg/375px-IN-JH.svg.png'),
      States(
          'Karnataka',
          'Banglore',
          '1 November 1956',
          'Banglore',
          'Kannada',
          31,
          'Basavaraj Bommai',
          'Thawarchand Gehlot',
          '61,130,704',
          8,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/IN-KA.svg/375px-IN-KA.svg.png'),
      States(
          'Kerela',
          'Thiruvananthapuram',
          '1 November 1956',
          'Thiruvananthapuram',
          'Malyalam',
          14,
          'Pinarayi Vijayan',
          'Arif Mohammad Khan',
          '34,630,192',
          13,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IN-KL.svg/375px-IN-KL.svg.png'),
      States(
          'Madhya Pradesh',
          'Bhopal',
          '1 November 1956',
          'Indore',
          'Hindi',
          52,
          'Shivraj Singh Chouhan',
          'Mangubhai C. Patel',
          '72,626,809',
          5,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/IN-MP.svg/375px-IN-MP.svg.png'),
      States(
          'Maharashtra',
          'Mumbai',
          '1 May 1960',
          'Mumbai',
          'Marathi',
          36,
          'Uddhav Thackeray',
          'Bhagat Singh Koshyari',
          '112,374,333',
          2,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/IN-MH.svg/375px-IN-MH.svg.png'),
      States(
          'Manipur',
          'Imphal',
          '15 October 1949',
          'Imphal',
          'Manipuri',
          16,
          'N. Biren Singh',
          'La. Ganesan',
          '2,855,794',
          23,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/IN-MN.svg/250px-IN-MN.svg.png'),
      States(
          'Meghalaya',
          'Shillong',
          '21 January 1972',
          'Shillong',
          'English',
          12,
          'Conrad Sangma',
          'Satya Pal Malik',
          '2,964,007',
          22,
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/IN-ML.svg/250px-IN-ML.svg.png'),
    ];
    return states;
  }
}
